version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dotnet-test-samples"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kgurv0ac87fw"
s3_prefix = "dotnet-test-samples"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
